[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 2000
remappings = ["@openzeppelin/=node_modules/@openzeppelin/contracts",]

[rpc_endpoints]
opbnb_testnet = "${OPBNB_TESTNET_RPC}"
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
blast_sepolia = "${BLAST_SEPOLIA_RPC_URL}"
scroll_sepolia = "${SCROLL_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"

#[etherscan]
#sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
